default_context:
  project_name: 'template'
  project_slug: 'template'
  domain_main: 'template.com'
  domain_staging: 'stag.template.com'
  docker_swarm_stack_name_main: 'template-com'
  docker_swarm_stack_name_staging: 'stag-template-com'
  secret_key: 'e477090fe0bf03471c2d95202547a1737d748f9a6698e6f7b1475fb4d1920230'
  first_superuser: 'admin@template.com'
  first_superuser_password: '9ce6ec014fd4b9588cc8c2001fe4fc2cb725d839bc559ef5d4eb0cc6a5f6ea09'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.template.com", "https://stag.template.com", "https://template.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@template.com'
  postgres_password: '399506a9fa65f59d0b7c24c413c5d6f73a6e81527e40b8f7072907786345ac8d'
  pgadmin_default_user: 'admin@template.com'
  pgadmin_default_user_password: '9ce6ec014fd4b9588cc8c2001fe4fc2cb725d839bc559ef5d4eb0cc6a5f6ea09'
  traefik_constraint_tag: 'template.com'
  traefik_constraint_tag_staging: 'stag.template.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:9ce6ec014fd4b9588cc8c2001fe4fc2cb725d839bc559ef5d4eb0cc6a5f6ea09'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
